name: dttn_khtn
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  background_fetch: ^0.1.1
  firebase_messaging: ^2.1.0
  google_sign_in: ^3.2.4
  firebase_auth: ^0.6.6
  firebase_database: ^1.0.5
  shared_preferences: ^0.4.3
  http: ^0.12.0
  cached_network_image: ^0.5.1
  cloud_firestore: 0.8.2+3
  firebase_storage: ^1.0.4
  image_picker: ^0.3.1
  fluttertoast: ^2.1.2
  intl: ^0.15.7
  flutter_signin_button: ^0.2.4
  lazy_load_scrollview: ^0.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - images/logo_man_run.png
      - images/login_bg.jpg
      - images/avatar_empty.png
      - images/ic_female.png
      - images/ic_male.png
      - images/ic_game_money.png
      - images/mimi1.gif
      - images/mimi2.gif
      - images/mimi3.gif
      - images/mimi4.gif
      - images/mimi5.gif
      - images/mimi6.gif
      - images/mimi7.gif
      - images/mimi8.gif
      - images/mimi9.gif

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
